### ISSUE TITLE
Healing Report Issue

### ISSUE THREAD

**Issue by govinda007** [healenium/healenium-example#10]
I cloned this repository and opened in Intellij IDEA 2019.1.4 and installed "Locator Updater 1.9" plugin as mentioned in Healenium wiki page.
when I ran some of the test-cases, It generated healing report but it's displaying **undefined** instead of test case name.
Screenshot of Healing report is as follows.
![image](https://user-images.githubusercontent.com/34766130/79742362-549d2b80-8320-11ea-816c-bdf2d3edac5c.png)
Also, When I am clicking on **accept** button, Its displaying as accepted but not making any change in code base. IDE is showing fatal IDE error as follows:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.epam.sha.intellij.locatorupdater.handler.OpenFileMessageHandler.handle(OpenFileMessageHandler.java:47)
	at com.epam.sha.intellij.locatorupdater.notifier.SocketNotifier.handle(SocketNotifier.java:132)
	at com.epam.sha.intellij.locatorupdater.notifier.SocketNotifier.run(SocketNotifier.java:94)
	at java.lang.Thread.run(Thread.java:748)
``` 
Please help!

**Comment by nareshm1** [comment]
@govinda007  Could you please provide the github access to this code stack .. I can help on this
